### ISSUE TITLE
allow for upgrading the check-mk-agent

### ISSUE THREAD

**Issue by divansantana** [elnappo/ansible-role-check-mk-agent#26]
Seems to install the agent, but not allow for upgrading the agent
because state is set to present.

```yaml
- name: Install check_mk_agent
  package:
    name: check-mk-agent
    state: present
```

Would be nice to have an option to allow for latest, or a version.
