### ISSUE TITLE
Issue on Create cache time directories tasks when check_mk_agent_local_checks is defined without cache_time

### ISSUE THREAD

**Issue by roumano** [elnappo/ansible-role-check-mk-agent#31]
If we definie a check_mk_agent_local_checks without a cache_time ( it's not mandatory), the tasks `Create cache time directories` is failing 

Exemple how to reproduce the issue, create this variable : 
```
check_mk_agent_local_checks:
  sync_ldap_config:
    src: check_ldap_consistency_config
    cache_time: 3600
  sync_ldap_data:
    src: check_ldap_consistency_data
```
It's failing with this error : 
```
TASK [elnappo.check_mk_agent : Create cache time directories] *************************************************************************************************
fatal: [ldap1a]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'cache_time'\n\nThe error appears to be in '/roles/elnappo.check_mk_agent/tasks/main.yml': line 42, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create cache time directories\n  ^ here\n"}
```

To fix this issue, need to a when condition in tasks `Create cache time directories` :  
```
  when: item.value.cache_time is defined
```
